### PR TITLE
Miscellaneous optimizations throughout

### PR DESCRIPTION
**Pull request by scottmathson-auth0**
What an awesome site!

@moeamaya I am really liking your work/projects and I introduced my team @ Auth0 to your rellax library, very nice!

This PR includes commits that improve accessibility throughout and other, misc. items.

### CODE REVIEW

**Comment by moeamaya** [comment]
Thanks for your help Scott!

I like most of your changes and making the site more accessible is awesome!

Can you change one thing though? The "DeSForM" spelling is intentional by the client. The stylized spelling is part of their branding. 

Thanks!

**Comment by scottmathson-auth0** [comment]
Awesome, thanks Moe!

> Can you change one thing though? The "DeSForM" spelling is intentional by the client. The stylized spelling is part of their branding.

So I was actually changing the metadata to _have_ that capitalization consistency (I'm all about brand consistency), as it doesn't currently. [Reference commit here](https://github.com/moeamaya/designlab/pull/18/commits/ab5a9d7a4cc07116451c72e32e1f9021d9bd724b) Are you saying want it changed back to the "Desform" case, then?

**Comment by scottmathson-auth0** [comment]
As it currently is:
Google SERP preview

Twitter card validator preview

**Comment by moeamaya** [comment]
Ohhhh great catch. Thank you.

**Comment by scottmathson-auth0** [comment]
Noticed those duplicated open graph tags too on a second look ^ and added twitter tags.

Good to merge if you like/approve the updates! 🤘

**Pull request merged**
